services:
  ingestion:
    build:
      context: .
      dockerfile: ./ingestion_api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      EVENT_BUCKET: ${EVENT_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: us-east-2