name: product_view
version: 2
description: User views a product

timestamp_field: ts

schema:
  user_id: string
  visit_id: string
  product_id: string
  request_id: string
  dwell_time: float
  ts: timestamp

default_destination: analytics_db